### ISSUE TITLE
Possibility to compile spiel and it's providers without flatpak

### ISSUE THREAD

**Issue by zywek123** [eeejay/spiel#38]
Hi.
    Maybe it is currently possible, but i don't know, how to do it.
    Is any way or will be any way in the future, to compile and use spiel with it's speech providers without using flatpak? If yes, What are the steps i should do, to have it working after compiling spiel from source?

**Comment by andyholmes** [comment]
Hi, I have opened a merge request in Orca with instructions at https://gitlab.gnome.org/GNOME/orca/-/merge_requests/189 which may be helpful.

Be warned that today we're coordinating a first release of Spiel with support in Orca, so you might need to wait and update your git clones if something doesn't work. Here's the instructions for quick reference:

### Building Spiel from Source

For advanced users, Spiel and providers may be built from source. If you are
unsure, consider using the available Flatpaks and consult the documentation for
your distribution before proceeding.

1. Build and install Orca with support for Spiel

   ```sh
   # Clone the repository
   https://gitlab.gnome.org/GNOME/orca.git
   cd orca

   # Build and install
   meson setup --force-fallback-for=spiel -Dspiel=true _build
   meson compile -C _build
   meson install -C _build
   ```

2. Next build and install a provider

   ```sh
   # Clone the repository, then select a provider in the "providers/" directory
   git clone https://github.com/eeejay/spiel-demos.git
   cd spiel-demos/providers/espeak

   # Build and install
   meson setup _build
   meson compile -C _build
   meson install -C _build
   ```

Once you start Orca, it will start the provider(s) automatically and you should be able to select one from the preferences. If you're not using Orca, then creating a new `SpielSpeaker` with the library will do that, too.

**Comment by eeejay** [comment]
spiel is a client library that can be used to interact with speech providers over the session bus. It has a meson build system and can be built and installed like any other library or project. Because it is just a library it will not do anything interesting once it is installed. You need to install speech providers as well. The easiest way to get speech providers is in the spiel-demos repo using flatpaks. Like Andy says above you can also install those manually with meson if you wish. The goal of the flatpaks is to make the process easy so you don't need to worry about system dependencies.

Once you have speech providers you can use Orca's experimental Spiel support to test the setup. If you don't want to risk switching to spiel just yet, you can use the `spiel` command line to speak phrases and see that it works.
